language: node_js
node_js:
  - '9.2'
  - '8.0'

services:
  - mongodb

script:
  - yarn client:server:test

notifications:
  email:
    recipients:
      - ajarombek95@gmail.com
    on_success: always
    on_failure: always