# Docker Compose configuration in the PROD environment
# Author: Andrew Jarombek
# Date: 5/19/2019

version: '3.7'
services:
  app:
    build: ../../
    dockerfile: aws.dockerfile
    environment:
      - NODE_ENV=production