name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      #options: --user 1001

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn
          yarn client:dev
          yarn server:dev
        env:
          BUILD_ENV: local

      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn server:deploy