name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  format_lint:
    runs-on: ubuntu-latest
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        run: yarn

      - name: Lint JavaScript Code
        run: yarn lint

      - name: Format JavaScript Code
        run: yarn prettier:write

      - name: Commit and Push Formatting Changes
        run: |
          git config --global --add safe.directory $(realpath .)
          commit_hash=$(git rev-parse HEAD)
          echo "Current commit hash: $commit_hash"
  
          current_branch=$(git branch --contains $commit_hash)
          echo "Current branch: $current_branch"
          
          git checkout $current_branch
  
          git config user.email "andrew@jarombek.com"
          git config user.name "Andrew Jarombek"
          git add .
          git commit -m "Format Code with Prettier"
          git push
